import React, {Component} from 'react';
class viewEvents extends Component {   
    
    render() {
       return  (
            <a href= "https://georgianservices.azurewebsites.net/Pages/ImportantDates.aspx?SPHostUrl=https%3a%2f%2fgeorgiancollege.sharepoint.com%2fsites%2fstudent&SPHostTitle=Home&SPAppWebUrl=https%3a%2f%2fgeorgiancollege-ce6491b1a96565.sharepoint.com%2fsites%2fstudent%2fGeorgianServicesAddIn&SPLanguage=en-US&SPClientTag=0&SPProductNumber=16.0.6511.1209&CategoryName=important-dates&TimeSpanMonths=1&SenderId=94792B182&AppContextToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNzllMmIzNy1lYTg3LTQ3ODktYjNkMC02MDZlMzkyMzk2ZWEvZ2VvcmdpYW5zZXJ2aWNlcy5henVyZXdlYnNpdGVzLm5ldEBkYTlhOTRiNi00NjgxLTQ5YmMtYmQ3Yy1iYWI5ZWFjMGFkM2MiLCJpc3MiOiIwMDAwMDAwMS0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDBAZGE5YTk0YjYtNDY4MS00OWJjLWJkN2MtYmFiOWVhYzBhZDNjIiwiaWF0IjoxNDk1NzQ0NjE5LCJuYmYiOjE0OTU3NDQ2MTksImV4cCI6MTQ5NTc0ODUxOSwiYXBwY3R4Ijoie1wiQ2FjaGVLZXlcIjpcIjRzSUhvY0d0SHJyR2JWY2E0VkFHcEVvNDlaUXdpOU55TkdUc01BdFRyQW89XCIsXCJOZXh0Q2FjaGVLZXlcIjpudWxsLFwiU2VjdXJpdHlUb2tlblNlcnZpY2VVcmlcIjpcImh0dHBzOi8vYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldC90b2tlbnMvT0F1dGgvMlwifSIsImFwcGN0eHNlbmRlciI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEBkYTlhOTRiNi00NjgxLTQ5YmMtYmQ3Yy1iYWI5ZWFjMGFkM2MiLCJpc2Jyb3dzZXJob3N0ZWRhcHAiOiJ0cnVlIiwicmVmcmVzaHRva2VuIjoiSUFBQUFLdHJzT1JXckVUd19UQzRtcDJOejJnSW40V09oOEw3ZXNUWnJDcmFsZDR4TDRkSmlmczJGNGJRQV8zTEFNMEJpSmxORXlRVmZIUG5wZ2o5NTJTUE9neEdlT0drM19FWmI0RzJnczZSdGFFUklTdlFVclZ0dHVUV1VuN3dURXN0Wk9WS1cyZWNYTERYaE0zd2JZMWJscGx4b0NBVllxR3VteDJQRzViOFllUHJrT0NtRmlkWUU5eHNRVmhObU1xVWd1a29Lc2RpSDYwQUtnSF9fUF9Za0tvS3gtLUlDQkxoNkM5U1ZuaVFYT0FQOWlKS2xmRkd1bWpMUXBVZkt5ZnpEWmFzLXZlcnByN2JLT29xZjFYeXBjdkRzaldPYmlMVjVvVmstVEdaaHRVeDZPWEVHZk9NVzZTYlRocURWVk10VXcifQ.UsxTcESzJa_tt7HPofTvXEiL4XeMKQN4N_iaIEPzACc">View all events</a>
        );
    }
}



export default (viewEvents);